apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 705070889123.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 705070889123.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: d5d6d588
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
