---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: M2M-EksCluster-Production-20240329
  region: ap-northeast-2
fargateProfiles:
  - name: frontend-fargate-profile
    selectors:
      - namespace: default
        labels:
          app: frontend-fargate
